// import './globals.css'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

import { cn } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// import Drawer from "@/components/Drawer";
import { fontSans } from "@/lib/fonts";
import Navbar from "@/components/navigation/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "relative flex min-h-screen w-full flex-col justify-center scroll-smooth bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <main className="flex">
          {/* <Drawer /> */}
          <Navbar />
          <div className="w-full">
            <header className={cn("hidden w-full z-50 bg-white border-b")}>
              <nav className="flex items-center h-16 px-8"></nav>
            </header>
            <div
              className={cn(
                "w-full space-y-4 md:p-8 p-4 pt-6 h-screen overflow-auto bg-slate-50 dark:bg-slate-950",
                {
                  "h-[calc(100vh-4rem)]": false,
                }
              )}
            >
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
